Traceback (most recent call last):
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python\Miniconda\envs\workspace_JB\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python\Miniconda\envs\workspace_JB\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
flash1 = flash_isothermal_ssi(mr1, z, ssi_use_opt=True, ssi_eq_max_iter=30, save_residuals=True).flash_isothermal_ssi_run(P, T, phases, cw=0.0)
flash1.comp_mole_frac, flash1.it
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_18628\2523847165.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mflash1[0m [1;33m=[0m [0mflash_isothermal_ssi[0m[1;33m([0m[0mmr1[0m[1;33m,[0m [0mz[0m[1;33m,[0m [0mssi_use_opt[0m[1;33m=[0m[1;32mTrue[0m[1;33m,[0m [0mssi_eq_max_iter[0m[1;33m=[0m[1;36m30[0m[1;33m,[0m [0msave_residuals[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m.[0m[0mflash_isothermal_ssi_run[0m[1;33m([0m[0mP[0m[1;33m,[0m [0mT[0m[1;33m,[0m [0mphases[0m[1;33m,[0m [0mcw[0m[1;33m=[0m[1;36m0.0[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mflash1[0m[1;33m.[0m[0mcomp_mole_frac[0m[1;33m,[0m [0mflash1[0m[1;33m.[0m[0mit[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'flash_isothermal_ssi' is not defined
NameError: name 'flash_isothermal_ssi' is not defined

